CREATE TABLE `pms_passing_vehicle_record` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `tenantId` bigint(20) unsigned NOT NULL COMMENT '租户ID',
  `parkingId` bigint(20) unsigned NOT NULL COMMENT '停车场ID',
  `parkingName` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '停车场名称',
  `parkingCode` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '停车场编号',
  `gateId` bigint(20) unsigned DEFAULT NULL COMMENT '出入口ID',
  `parkingLotId` bigint(20) DEFAULT NULL COMMENT '泊位ID',
  `parkingLotCode` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '泊位code',
  `parkingLotNumber` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '泊位编号',
  `passingNo` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '平台过车流水号',
  `passingUuid` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '平台过车唯一编号',
  `hikPassingId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '海康平台过车ID',
  `aliPassingId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '阿里平台过车ID',
  `cardNumber` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '停车卡号',
  `codeNumber` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '停车码',
  `plateNumber` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '车牌号',
  `plateNoExist` tinyint(1) DEFAULT '0' COMMENT '是否有无车牌 0 无车牌 1 有车牌',
  `plateColor` tinyint(4) unsigned DEFAULT NULL COMMENT '车牌颜色',
  `carType` tinyint(4) unsigned DEFAULT NULL COMMENT '车辆类型',
  `plateNumberConfidence` int(11) DEFAULT NULL COMMENT '车牌置信度',
  `passingType` tinyint(4) unsigned DEFAULT '0' COMMENT '过车类型  0 未知 1.入车 2.出车 ',
  `confidence` tinyint(4) unsigned DEFAULT NULL COMMENT '过车置信度',
  `parkingType` tinyint(4) unsigned DEFAULT NULL COMMENT '停车类型',
  `abnormal` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否异常放行：0 正常；1异常放行',
  `passTime` datetime DEFAULT NULL COMMENT '过车时间',
  `entryTime` datetime DEFAULT NULL COMMENT '入车时间',
  `exitTime` datetime DEFAULT NULL COMMENT '出车时间',
  `dataSource` tinyint(4) DEFAULT '1' COMMENT '过车数据来源',
  `photoUploaded` tinyint(4) unsigned DEFAULT '0' COMMENT '过车图片是否上传',
  `photoCount` tinyint(4) unsigned DEFAULT '0' COMMENT '图片数量',
  `uploadedDate` datetime DEFAULT NULL COMMENT '图片上传时间',
  `proofStatus` tinyint(1) DEFAULT '0' COMMENT '校对状态 0:未校对  1:已校对',
  `proofUserId` bigint(20) DEFAULT NULL COMMENT '校对用户',
  `proofDate` datetime DEFAULT NULL COMMENT '校对时间',
  `remark` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `creatorUserId` bigint(20) DEFAULT NULL COMMENT '创建者',
  `creationTime` datetime DEFAULT NULL COMMENT '创建时间',
  `lastModifierUserId` bigint(20) DEFAULT NULL COMMENT '更新者',
  `lastModificationTime` datetime DEFAULT NULL COMMENT '更新时间',
  `deleterUserId` bigint(20) DEFAULT NULL COMMENT '删除者',
  `deletionTime` datetime DEFAULT NULL COMMENT '删除时间',
  `deleted` tinyint(1) DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`id`),
  KEY `idx_tenantId` (`tenantId`),
  KEY `idx_parkingId` (`parkingId`),
  KEY `idx_parkingLotId` (`parkingLotId`),
  KEY `idx_plateNumber` (`plateNumber`),
  KEY `idx_passingUuid` (`passingUuid`),
  KEY `idx_passingNo` (`passingNo`),
  KEY `idx_dataSource` (`dataSource`),
  KEY `idx_photoUploaded` (`photoUploaded`)
) ENGINE=InnoDB AUTO_INCREMENT=47188 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='过车记录表';

CREATE TABLE `pms_parking_record_image` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `tenantId` bigint(20) unsigned NOT NULL COMMENT '租户ID',
  `parkingId` bigint(20) NOT NULL COMMENT '停车场ID',
  `bizId` bigint(20) unsigned NOT NULL COMMENT '停车记录ID',
  `bizNo` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '过车/停车记录流水号',
  `bizType` tinyint(4) NOT NULL COMMENT '业务类型  1.过车 2.停车',
  `uuid` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '图片唯一ID',
  `url` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '图片URL',
  `type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '图片文件类型',
  `creatorUserId` bigint(20) DEFAULT NULL COMMENT '创建者',
  `creationTime` datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `pms_parking_image_tenantId` (`tenantId`,`bizNo`,`bizType`),
  KEY `pms_parking_image_bizId` (`tenantId`,`bizId`,`bizType`)
) ENGINE=InnoDB AUTO_INCREMENT=2486 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='停车照片表';


CREATE TABLE `pms_parking_vehicle_record` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `tenantId` bigint(20) unsigned NOT NULL COMMENT '租户ID',
  `parkingId` bigint(20) NOT NULL COMMENT '停车场ID',
  `parkingName` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '停车场名称',
  `parkingCode` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '停车场编号',
  `parkingLotId` bigint(20) DEFAULT NULL COMMENT '泊位ID',
  `parkingLotCode` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '泊位code',
  `parkingLotNumber` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '泊位编号',
  `intoRecordNo` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '入车记录流水号',
  `cardNumber` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '停车卡号',
  `codeNumber` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '停车码',
  `plateNumber` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '车牌号',
  `plateColor` tinyint(4) DEFAULT NULL COMMENT '车牌颜色',
  `carType` tinyint(4) DEFAULT NULL COMMENT '车辆类型',
  `startTime` datetime DEFAULT NULL COMMENT '停车开始时间',
  `creatorUserId` bigint(20) DEFAULT NULL COMMENT '创建者',
  `creationTime` datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_parkingId` (`parkingId`),
  KEY `idx_parkingLotId` (`parkingLotId`),
  KEY `idx_plateNumber` (`plateNumber`),
  KEY `idx_plateColor` (`plateColor`),
  KEY `idx_carType` (`carType`)
) ENGINE=InnoDB AUTO_INCREMENT=17051 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='停车场在停车辆表';

CREATE TABLE `spe_inspect_record` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `tenantId` bigint(20) unsigned NOT NULL COMMENT '租户ID',
  `recordId` bigint(20) unsigned NOT NULL COMMENT '停车记录ID',
  `recordNo` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '停车记录流水号',
  `parkingId` bigint(20) unsigned NOT NULL COMMENT '停车场ID',
  `parkingLotId` bigint(20) DEFAULT NULL COMMENT '泊位ID',
  `cardNumber` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '停车卡号',
  `codeNumber` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '停车码',
  `plateNumber` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '车牌号',
  `plateColor` tinyint(4) unsigned DEFAULT NULL COMMENT '车牌颜色',
  `carType` tinyint(4) unsigned DEFAULT NULL COMMENT '车辆类型',
  `parkingType` tinyint(4) unsigned DEFAULT NULL COMMENT '停车类型',
  `startTime` datetime DEFAULT NULL COMMENT '停车开始时间',
  `endTime` datetime DEFAULT NULL COMMENT '停车结束时间',
  `status` tinyint(4) DEFAULT '0' COMMENT '状态',
  `inspectUserId` bigint(20) unsigned NOT NULL COMMENT '巡检员收费员ID',
  `inspectTime` datetime DEFAULT NULL COMMENT '巡查时间',
  `inspectReason` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '异常原因，1 -剩余车位数不正确，2 -车牌号码不匹配 3 车牌颜色不匹配 4 泊位不匹配 5 车型不匹配 6 入场时间不匹配',
  `inspectResult` smallint(6) DEFAULT NULL COMMENT '巡查结果，1 已处理 2 未处理',
  `description` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '描述信息',
  `creatorUserId` bigint(20) DEFAULT NULL COMMENT '创建者',
  `creationTime` datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_inspect_tenantId` (`tenantId`),
  KEY `idx_inspect_recordId` (`tenantId`,`recordId`),
  KEY `idx_inspect_parkingId` (`tenantId`,`parkingId`),
  KEY `idx_inspect_userId` (`tenantId`,`inspectUserId`),
  KEY `idx_inspect_plateNumber` (`plateNumber`)
) ENGINE=InnoDB AUTO_INCREMENT=74 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='巡检记录表';

CREATE TABLE `pms_parking_record` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `tenantId` bigint(20) unsigned NOT NULL COMMENT '租户ID',
  `recordNo` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '停车记录流水号',
  `hikParkingRecordId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '海康平台停车记录ID',
  `aliParkingRecordId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '阿里平台停车记录ID',
  `parkingId` bigint(20) NOT NULL COMMENT '停车场ID',
  `parkingName` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '停车场名称',
  `parkingCode` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '停车场编号',
  `parkingLotId` bigint(20) DEFAULT NULL COMMENT '泊位ID',
  `parkingLotCode` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '泊位code',
  `parkingLotNumber` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '泊位编号',
  `intoRecordNo` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '入车车流水号',
  `outRecordNo` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '出车车流水号',
  `cardNumber` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '停车卡号',
  `codeNumber` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '停车码',
  `plateNumber` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '车牌号',
  `plateColor` tinyint(4) unsigned DEFAULT NULL COMMENT '车牌颜色',
  `carType` tinyint(4) unsigned DEFAULT NULL COMMENT '车辆类型',
  `parkingType` tinyint(4) unsigned DEFAULT NULL COMMENT '停车类型',
  `startTime` datetime DEFAULT NULL COMMENT '停车开始时间',
  `endTime` datetime DEFAULT NULL COMMENT '停车结束时间',
  `periodLength` int(10) unsigned DEFAULT '0' COMMENT '停车时长：分钟',
  `status` tinyint(4) DEFAULT '0' COMMENT '状态',
  `appointed` tinyint(1) DEFAULT '0' COMMENT '是否预约停车 0 否 1 是',
  `appointOrderNo` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '预约订单号',
  `appointRuleId` bigint(20) unsigned DEFAULT NULL COMMENT '预约收费规则ID：入车时的预约规则',
  `chargeId` bigint(20) unsigned DEFAULT NULL COMMENT '收费规则ID：入车时的收费规则',
  `payableAmount` int(10) unsigned DEFAULT '0' COMMENT '总金额：单位分',
  `creatorUserId` bigint(20) DEFAULT NULL COMMENT '创建者',
  `creationTime` datetime DEFAULT NULL COMMENT '创建时间',
  `lastModifierUserId` bigint(20) DEFAULT NULL COMMENT '更新者',
  `lastModificationTime` datetime DEFAULT NULL COMMENT '更新时间',
  `deleterUserId` bigint(20) DEFAULT NULL COMMENT '删除者',
  `deletionTime` datetime DEFAULT NULL COMMENT '删除时间',
  `deleted` tinyint(1) DEFAULT '0' COMMENT '删除标记',
  `version` bigint(20) DEFAULT '1' COMMENT '版本号',
  PRIMARY KEY (`id`),
  KEY `idx_parkingId` (`parkingId`),
  KEY `idx_parkingLotId` (`parkingLotId`),
  KEY `idx_plateNumber` (`plateNumber`),
  KEY `idx_appointOrderNo` (`appointOrderNo`)
) ENGINE=InnoDB AUTO_INCREMENT=16582 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='平台停车记录表表';

CREATE TABLE `ord_hikvision_parking_order` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `tenantId` bigint(20) NOT NULL COMMENT '租户ID',
  `record` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '平台停车记录编号',
  `orderNo` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '平台停车账单编号',
  `billNo` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '账单编号',
  `parkingId` bigint(20) DEFAULT NULL COMMENT '平台停车场ID',
  `plateNumber` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '车牌号',
  `plateColor` tinyint(4) DEFAULT NULL COMMENT '车牌颜色',
  `carType` tinyint(4) DEFAULT NULL COMMENT '车辆类型',
  `parkCode` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '停车场编号',
  `enterTime` datetime DEFAULT NULL COMMENT '车辆进场时间',
  `costTime` datetime DEFAULT NULL COMMENT '结算时间',
  `parkPeriodTime` tinyint(4) DEFAULT NULL COMMENT '停车时长(分钟)',
  `totalCost` tinyint(4) DEFAULT NULL COMMENT '总收费金额(单位：分)',
  `payTime` datetime DEFAULT NULL COMMENT '支付时间',
  `payAmount` tinyint(4) DEFAULT NULL COMMENT '总收费金额(单位：分)',
  `payType` tinyint(4) DEFAULT NULL COMMENT '支付方式 4支付宝5 微信11账户余额（云平台的账户）',
  `status` tinyint(4) DEFAULT '0' COMMENT '账单状态 0 已创建 1 支付中 2 等待支付结果 3 已支付 4 支付失败',
  `creatorUserId` bigint(20) DEFAULT NULL COMMENT '创建者',
  `creationTime` datetime DEFAULT NULL COMMENT '创建时间',
  `lastModifierUserId` bigint(20) DEFAULT NULL COMMENT '更新者',
  `lastModificationTime` datetime DEFAULT NULL COMMENT '更新时间',
  `deleterUserId` bigint(20) DEFAULT NULL COMMENT '删除者',
  `deletionTime` datetime DEFAULT NULL COMMENT '删除时间',
  `deleted` tinyint(1) DEFAULT '0' COMMENT '删除标记',
  `version` bigint(20) DEFAULT '1' COMMENT '版本号',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='海康停车账单表';


CREATE TABLE `ord_parking_appointment_order` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `tenantId` bigint(20) unsigned NOT NULL COMMENT '租户ID',
  `parkingId` bigint(20) NOT NULL COMMENT '停车场ID',
  `parkingName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '停车场名称',
  `parkingLotId` bigint(20) DEFAULT NULL COMMENT '泊位ID',
  `parkingLotCode` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '车位编号',
  `chargeInfoId` bigint(20) NOT NULL COMMENT '停车场收费信息ID',
  `appointInfoId` bigint(20) NOT NULL COMMENT '停车场预约信息ID',
  `orderNo` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '平台平台预约记录流水号',
  `plateNumber` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '车牌号',
  `plateColor` tinyint(4) DEFAULT NULL COMMENT '车牌颜色',
  `carStyle` tinyint(4) DEFAULT NULL COMMENT '车辆类型',
  `scheduleDate` date DEFAULT NULL COMMENT '预约下单日期',
  `scheduleTime` datetime DEFAULT NULL COMMENT '预约预计开始时间',
  `scheduleLength` int(11) DEFAULT NULL COMMENT '预计停车时长(分钟)',
  `deadlineTime` datetime DEFAULT NULL COMMENT '预约有效截止时间',
  `payLimit` int(11) DEFAULT NULL COMMENT '支付时限(分钟)',
  `payLimitTime` datetime DEFAULT NULL COMMENT '支付截止时间',
  `payWayName` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '支付通道名称',
  `appointStatus` tinyint(4) DEFAULT '1' COMMENT '预约状态',
  `payStatus` tinyint(4) DEFAULT '0' COMMENT '支付状态',
  `payTime` datetime DEFAULT NULL COMMENT '支付时间',
  `payAmount` int(10) unsigned DEFAULT '0' COMMENT '预约支付金额(分)',
  `actualPayAmount` int(10) unsigned DEFAULT '0' COMMENT '预约实付金额(分)',
  `refundAmount` int(10) unsigned DEFAULT '0' COMMENT '退还金额(分)',
  `canCancel` tinyint(1) DEFAULT '0' COMMENT '是否允许用户手动取消',
  `overTimeCancel` tinyint(1) DEFAULT '0' COMMENT '是否超时取消',
  `cancelTimeLimit` datetime DEFAULT NULL COMMENT '取消时限',
  `cancelTime` datetime DEFAULT NULL COMMENT '取消时间',
  `cancelFee` int(10) unsigned DEFAULT '0' COMMENT '取消费用',
  `cancelReason` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '取消原因',
  `remark` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '备注',
  `entrance` tinyint(1) DEFAULT '0' COMMENT '是否入场(0 未入场 1 入场)',
  `customerUserId` bigint(20) NOT NULL COMMENT '车主用户ID',
  `creatorUserId` bigint(20) DEFAULT NULL COMMENT '创建者',
  `creationTime` datetime DEFAULT NULL COMMENT '创建时间',
  `lastModifierUserId` bigint(20) DEFAULT NULL COMMENT '更新者',
  `lastModificationTime` datetime DEFAULT NULL COMMENT '更新时间',
  `deleterUserId` bigint(20) DEFAULT NULL COMMENT '删除者',
  `deletionTime` datetime DEFAULT NULL COMMENT '删除时间',
  `deleted` tinyint(1) DEFAULT '0' COMMENT '删除标记',
  `version` bigint(20) DEFAULT '1' COMMENT '版本号',
  PRIMARY KEY (`id`),
  KEY `idx_tenantId` (`tenantId`),
  KEY `idx_parkingId` (`parkingId`),
  KEY `idx_customerUserId` (`customerUserId`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='平台停车预约表';

CREATE TABLE `ord_parking_order` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `tenantId` bigint(20) NOT NULL COMMENT '租户ID',
  `recordNo` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '平台停车记录流水号',
  `orderNo` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '平台停车账单流水号',
  `hikBillNo` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '海康平台账单编号',
  `parkingId` bigint(20) NOT NULL COMMENT '平台停车场ID',
  `chargeInfoId` bigint(20) NOT NULL COMMENT '停车场收费信息ID',
  `parkingName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '停车场名称',
  `parkingLotId` bigint(20) DEFAULT NULL COMMENT '平台泊位ID',
  `parkingLotCode` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '车位编号',
  `plateNumber` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '车牌号',
  `plateColor` tinyint(4) DEFAULT NULL COMMENT '车牌颜色',
  `carStyle` tinyint(4) DEFAULT NULL COMMENT '车辆类型',
  `startTime` datetime DEFAULT NULL COMMENT '停车开始时间',
  `endTime` datetime DEFAULT NULL COMMENT '停车结束时间',
  `artificial` tinyint(1) DEFAULT '0' COMMENT '是否手工单 0 否 1 是',
  `parkingLength` bigint(20) DEFAULT '0' COMMENT '停车时长(秒)',
  `freeLength` bigint(20) DEFAULT '0' COMMENT '免费停车时长(秒)',
  `chargeLength` bigint(20) DEFAULT '0' COMMENT '收费停车时长(秒)',
  `chargeMode` tinyint(4) DEFAULT NULL COMMENT '收费模式 1:离场前收费 2: 离场后收费',
  `status` tinyint(4) DEFAULT NULL COMMENT '停车状态',
  `hikSyncStatus` tinyint(4) DEFAULT '0' COMMENT '海康平台账单同步状态(0 未创建 1 已创建 2 已支付确认)',
  `appointed` tinyint(1) DEFAULT '0' COMMENT '是否预约停车 0 否 1 是',
  `appointOrderNo` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '预约订单号',
  `settle` tinyint(1) DEFAULT '0' COMMENT '是否已结算 0 未结算 1 已结算',
  `settleOrderNo` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '结算订单号',
  `settleAmount` int(10) unsigned DEFAULT '0' COMMENT '结算金额(分)',
  `settleTime` datetime DEFAULT NULL COMMENT '结算时间',
  `limitFree` tinyint(1) DEFAULT '0' COMMENT '是否限免停车 0 未结算 1 已结算',
  `payable` tinyint(1) DEFAULT '1' COMMENT '是否可以支付0 不可支付 1 可以支付',
  `needPay` tinyint(1) DEFAULT '1' COMMENT '是否需要支付0 无需支付 1 需要支付',
  `freePayReason` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '免于支付说明',
  `payableAmount` int(10) unsigned DEFAULT '0' COMMENT '应付金额(分)',
  `payStatus` tinyint(4) DEFAULT '0' COMMENT '支付状态 0 :未支付 1:已支付  2:支付中',
  `actualPayAmount` int(10) unsigned DEFAULT '0' COMMENT '实付金额(分)',
  `payTime` datetime DEFAULT NULL COMMENT '支付时间',
  `payedUserId` bigint(20) DEFAULT NULL COMMENT '支付用户ID',
  `payWay` tinyint(4) DEFAULT NULL COMMENT '支付方式(根据PayWayEnum)',
  `payTypeName` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '支付类型',
  `remark` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `editor` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '编辑人员',
  `creatorUserId` bigint(20) DEFAULT NULL COMMENT '创建者',
  `creationTime` datetime DEFAULT NULL COMMENT '创建时间',
  `lastModifierUserId` bigint(20) DEFAULT NULL COMMENT '更新者',
  `lastModificationTime` datetime DEFAULT NULL COMMENT '更新时间',
  `deleterUserId` bigint(20) DEFAULT NULL COMMENT '删除者',
  `deletionTime` datetime DEFAULT NULL COMMENT '删除时间',
  `deleted` tinyint(1) DEFAULT '0' COMMENT '删除标记',
  `version` bigint(20) DEFAULT '1' COMMENT '版本号',
  PRIMARY KEY (`id`),
  KEY `idx_recordNo` (`recordNo`),
  KEY `idx_orderNo` (`orderNo`),
  KEY `idx_parkingId` (`parkingId`),
  KEY `idx_plateNumber` (`plateNumber`),
  KEY `idx_settleOrderNo` (`settleOrderNo`),
  KEY `idx_appointOrderNo` (`appointOrderNo`),
  KEY `idx_billNo` (`hikBillNo`)
) ENGINE=InnoDB AUTO_INCREMENT=46 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='停车订单表';

CREATE TABLE `ord_parking_settle_record` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `tenantId` bigint(20) unsigned DEFAULT NULL COMMENT '租户ID',
  `recordNo` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '停车记录单号',
  `orderNo` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '结算订单号',
  `startTime` datetime DEFAULT NULL COMMENT '结算开始时间',
  `endTime` datetime DEFAULT NULL COMMENT '结算结束时间',
  `status` tinyint(4) DEFAULT '0' COMMENT '结算状态',
  `settleMode` tinyint(4) DEFAULT '0' COMMENT '结算模式(1 离场前结算 2 离场后结算 )',
  `settleTime` datetime DEFAULT NULL COMMENT '结算时间',
  `settleAmount` int(10) unsigned DEFAULT '0' COMMENT '结算金额(元)',
  `creatorUserId` bigint(20) DEFAULT NULL COMMENT '创建者',
  `creationTime` datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='停车订单结算记录';



----------------------------------------------------------------------------------------------------
支付
----------------------------------------------------------------------------------------------------
CREATE TABLE `pay_trade_payment_order` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `tenantId` bigint(20) unsigned DEFAULT NULL COMMENT '租户ID',
  `orderNo` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '交易订单号',
  `transactionNo` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '支付业务订单号,对应支付宝tradeNo或微信支付outTradeNo',
  `orderFrom` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '订单来源',
  `bizOrderType` tinyint(4) DEFAULT NULL COMMENT '交易业务类型 ：消费、充值等',
  `bizOrderNo` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '交易业务订单号',
  `orderAmount` int(10) unsigned DEFAULT '0' COMMENT '订单金额',
  `productName` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '商品名称',
  `orderDate` date DEFAULT NULL COMMENT '订单日期',
  `orderTime` datetime DEFAULT NULL COMMENT '订单时间',
  `orderIp` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '下单IP(客户端IP,在网关页面获取)',
  `orderRefererUrl` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '从哪个页面链接过来的(可用于防诈骗)',
  `returnUrl` varchar(600) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '页面回调通知URL',
  `notifyUrl` varchar(600) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '后台异步通知URL',
  `orderPeriod` smallint(6) DEFAULT NULL COMMENT '订单有效期(单位分钟)',
  `expireTime` datetime DEFAULT NULL COMMENT '到期时间',
  `cancelReason` varchar(600) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '订单撤销原因',
  `cancelTime` datetime DEFAULT NULL COMMENT '订单撤销时间',
  `succeedPayTime` datetime DEFAULT NULL COMMENT '支付成功时间',
  `payWayCode` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '支付通道编号',
  `payWayName` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '支付通道名称',
  `payTypeCode` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '支付方式类型编号',
  `payTypeName` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '支付方式类型名称',
  `fundIntoType` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '资金流入类型',
  `refunded` tinyint(1) DEFAULT '0' COMMENT '是否退款(0:否,1: 是,默认值为:0)',
  `refundTimes` int(11) DEFAULT '0' COMMENT '退款次数(默认值为:0)',
  `successRefundAmount` int(10) unsigned DEFAULT '0' COMMENT '成功退款总金额',
  `succeedRefundTime` datetime DEFAULT NULL COMMENT '退款成功时间',
  `status` tinyint(4) DEFAULT NULL COMMENT '状态(参考枚举:PayStatusEnum)',
  `remark` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '支付备注',
  `customerUserId` bigint(20) NOT NULL COMMENT '车主用户ID',
  `creatorUserId` bigint(20) DEFAULT NULL COMMENT '创建者',
  `creationTime` datetime DEFAULT NULL COMMENT '创建时间',
  `lastModifierUserId` bigint(20) DEFAULT NULL COMMENT '更新者',
  `lastModificationTime` datetime DEFAULT NULL COMMENT '更新时间',
  `deleterUserId` bigint(20) DEFAULT NULL COMMENT '删除者',
  `deletionTime` datetime DEFAULT NULL COMMENT '删除时间',
  `deleted` tinyint(1) DEFAULT '0' COMMENT '删除标记',
  `version` bigint(20) DEFAULT '1' COMMENT '版本号',
  PRIMARY KEY (`id`),
  KEY `idx_tenantId` (`tenantId`)
) ENGINE=InnoDB AUTO_INCREMENT=54 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='平台支付订单表';


CREATE TABLE `pay_trade_payment_record` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `tenantId` bigint(20) unsigned DEFAULT NULL COMMENT '租户ID',
  `orderNo` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '交易订单号',
  `transactionNo` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '支付业务订单号,对应支付宝tradeNo或微信支付outTradeNo',
  `orderFrom` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '订单来源',
  `bizOrderType` tinyint(4) DEFAULT NULL COMMENT '交易业务类型 ：消费、充值等',
  `bizOrderNo` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '交易业务订单号',
  `orderAmount` int(10) unsigned DEFAULT '0' COMMENT '订单金额',
  `productName` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '商品名称',
  `payerUserId` bigint(20) DEFAULT NULL COMMENT '付款人ID',
  `payerUsername` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '付款人名称',
  `payerPayAmount` int(10) unsigned DEFAULT '0' COMMENT '付款方支付金额',
  `payerFee` int(10) unsigned DEFAULT '0' COMMENT '付款方手续费',
  `payerAccountType` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '付款方账户类型(参考账户类型枚举:AccountTypeEnum)',
  `receiverUserId` bigint(20) DEFAULT NULL COMMENT '收款人ID',
  `receiverUsername` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '收款人名称',
  `receiverPayAmount` int(10) unsigned DEFAULT '0' COMMENT '收款方支付金额',
  `receiverFee` int(10) unsigned DEFAULT '0' COMMENT '收款方手续费',
  `receiverAccountType` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '收款方账户类型(参考账户类型枚举:AccountTypeEnum)',
  `orderDate` date DEFAULT NULL COMMENT '订单日期',
  `orderTime` datetime DEFAULT NULL COMMENT '订单时间',
  `orderIp` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '下单IP(客户端IP,在网关页面获取)',
  `orderRefererUrl` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '从哪个页面链接过来的(可用于防诈骗)',
  `returnUrl` varchar(600) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '页面回调通知URL',
  `notifyUrl` varchar(600) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '后台异步通知URL',
  `platformIncome` int(10) unsigned DEFAULT '0' COMMENT '平台收入',
  `platformCost` int(10) unsigned DEFAULT '0' COMMENT '平台成本',
  `platformProfit` int(10) unsigned DEFAULT '0' COMMENT '平台利润',
  `feeRate` decimal(20,6) DEFAULT '0.000000' COMMENT '费率',
  `payWayCode` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '支付通道编号',
  `payWayName` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '支付通道名称',
  `payTypeCode` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '支付方式类型编号',
  `payTypeName` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '支付方式类型名称',
  `succeedPayTime` datetime DEFAULT NULL COMMENT '支付成功时间',
  `completeTime` datetime DEFAULT NULL COMMENT '完成时间',
  `fundIntoType` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '资金流入类型',
  `refunded` tinyint(1) DEFAULT '0' COMMENT '是否退款(0:否,1: 是,默认值为:0)',
  `refundTimes` int(11) DEFAULT '0' COMMENT '退款次数(默认值为:0)',
  `successRefundAmount` int(10) unsigned DEFAULT '0' COMMENT '成功退款总金额',
  `succeedRefundTime` datetime DEFAULT NULL COMMENT '退款成功时间',
  `status` tinyint(4) DEFAULT NULL COMMENT '状态(参考枚举:PayStatusEnum)',
  `remark` varchar(3000) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '备注',
  `customerUserId` bigint(20) NOT NULL COMMENT '车主用户ID',
  `creatorUserId` bigint(20) DEFAULT NULL COMMENT '创建者',
  `creationTime` datetime DEFAULT NULL COMMENT '创建时间',
  `lastModifierUserId` bigint(20) DEFAULT NULL COMMENT '更新者',
  `lastModificationTime` datetime DEFAULT NULL COMMENT '更新时间',
  `deleterUserId` bigint(20) DEFAULT NULL COMMENT '删除者',
  `deletionTime` datetime DEFAULT NULL COMMENT '删除时间',
  `deleted` tinyint(1) DEFAULT '0' COMMENT '删除标记',
  `version` bigint(20) DEFAULT '1' COMMENT '版本号',
  PRIMARY KEY (`id`),
  KEY `idx_tenantId` (`tenantId`)
) ENGINE=InnoDB AUTO_INCREMENT=70 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='平台支付记录表';


CREATE TABLE `pay_alipay_order` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `customerUserId` bigint(20) NOT NULL COMMENT '车主用户ID',
  `tenantId` bigint(20) unsigned DEFAULT NULL COMMENT '租户ID',
  `tradeNo` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '支付宝交易号',
  `outTradeNo` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '商户订单号',
  `outBizNo` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '商户返回退款申请的流水号',
  `subject` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '订单标题',
  `tradeStatus` tinyint(4) DEFAULT NULL COMMENT '交易状态',
  `totalAmount` decimal(12,2) NOT NULL COMMENT '订单金额',
  `receiptAmount` decimal(12,2) DEFAULT NULL COMMENT '实收金额',
  `invoiceAmount` decimal(12,2) DEFAULT NULL COMMENT '开票金额',
  `buyerPayAmount` decimal(12,2) DEFAULT NULL COMMENT '用户实际支付金额',
  `pointAmount` decimal(12,2) DEFAULT NULL COMMENT '集分宝金额',
  `refundFee` decimal(12,2) DEFAULT NULL COMMENT '总退款金额',
  `currencyType` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '货币类型',
  `body` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '商品描述',
  `gmtCreate` datetime DEFAULT NULL COMMENT '交易创建时间',
  `gmtPayment` datetime DEFAULT NULL COMMENT '交易付款时间',
  `gmtRefund` datetime DEFAULT NULL COMMENT '交易退款时间',
  `gmtClose` datetime DEFAULT NULL COMMENT '交易结束时间',
  `fundBillList` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '支付金额信息',
  `passbackParams` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '回传参数',
  `voucherDetailList` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '优惠券信息',
  `timeoutExpress` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '交易过期时间',
  `goodsType` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '商品主类型：0—虚拟类商品，1—实物类商品',
  `promoParams` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '优惠参数',
  `extendParams` text COLLATE utf8mb4_unicode_ci COMMENT '业务扩展参数',
  `enablePayChannels` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '可用渠道',
  `disablePayChannels` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '禁用渠道',
  `storeId` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '商户门店编号',
  `extUserInfo` text COLLATE utf8mb4_unicode_ci COMMENT '外部指定买家',
  `buyerId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '买家支付宝用户号',
  `buyerLogonId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '买家支付宝账号',
  `sellerId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '卖家支付宝用户号',
  `sellerEmail` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '卖家支付宝账号',
  `creatorUserId` bigint(20) DEFAULT NULL COMMENT '创建者',
  `creationTime` datetime DEFAULT NULL COMMENT '创建时间',
  `lastModifierUserId` bigint(20) DEFAULT NULL COMMENT '更新者',
  `lastModificationTime` datetime DEFAULT NULL COMMENT '更新时间',
  `deleterUserId` bigint(20) DEFAULT NULL COMMENT '删除者',
  `deletionTime` datetime DEFAULT NULL COMMENT '删除时间',
  `deleted` tinyint(1) DEFAULT '0' COMMENT '删除标记',
  `version` bigint(20) DEFAULT '1' COMMENT '版本号',
  PRIMARY KEY (`id`),
  KEY `idx_tenantId` (`tenantId`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='支付宝订单表';

CREATE TABLE `pay_weixin_pay_order` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `customerUserId` bigint(20) NOT NULL COMMENT '车主用户ID',
  `outTradeNo` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '商户订单号',
  `tenantId` bigint(20) unsigned DEFAULT NULL COMMENT '租户ID',
  `transactionId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '微信支付订单号',
  `prepayId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '预支付交易会话标识',
  `tradeState` tinyint(4) DEFAULT NULL COMMENT '交易状态',
  `tradeStateDesc` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '交易状态描述',
  `body` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '商品描述',
  `detail` text COLLATE utf8mb4_unicode_ci COMMENT '商品详情',
  `attach` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '附加数据',
  `tradeType` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '交易类型',
  `limitPay` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '指定支付方式',
  `sceneInfo` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '场景信息',
  `deviceInfo` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '设备号',
  `feeType` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '货币类型',
  `totalFee` int(10) unsigned DEFAULT NULL COMMENT '总金额',
  `cashFee` int(10) unsigned DEFAULT NULL COMMENT '现金支付金额',
  `cashFeeType` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '现金支付货币类型',
  `couponFee` int(11) DEFAULT NULL COMMENT '代金券使用数量',
  `settlementTotalFee` int(10) unsigned DEFAULT NULL COMMENT '应结订单金额',
  `spbillCreateIp` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '终端IP',
  `timeStart` datetime DEFAULT NULL COMMENT '交易起始时间',
  `timeEnd` datetime DEFAULT NULL COMMENT '支付完成时间',
  `goodsTag` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '订单优惠标记',
  `openid` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '用户标识',
  `subscribed` tinyint(1) DEFAULT '0' COMMENT '是否关注公众账号',
  `bankType` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '付款银行',
  `remark` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '备注',
  `creatorUserId` bigint(20) DEFAULT NULL COMMENT '创建者',
  `creationTime` datetime DEFAULT NULL COMMENT '创建时间',
  `lastModifierUserId` bigint(20) DEFAULT NULL COMMENT '更新者',
  `lastModificationTime` datetime DEFAULT NULL COMMENT '更新时间',
  `deleterUserId` bigint(20) DEFAULT NULL COMMENT '删除者',
  `deletionTime` datetime DEFAULT NULL COMMENT '删除时间',
  `deleted` tinyint(1) DEFAULT '0' COMMENT '删除标记',
  `version` bigint(20) DEFAULT '1' COMMENT ' 版本号',
  PRIMARY KEY (`id`),
  KEY `idx_tenantId` (`tenantId`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='微信支付订单表';






